### ISSUE TITLE
谢谢您的付出，是我需要的，请问怎么在webpack中npm install？

### ISSUE THREAD

**Issue by caicf** [samwang1027/mpvue-zanui#1]

**Comment by samwang1027** [comment]
可以详细阐述吗？

**Comment by wapznw** [comment]
非常感谢你的分享，希望能提交到npm仓库，能使用npm install mpvue-zanui安装

**Comment by samwang1027** [comment]
@wapznw 好的，我试试:smile:

**Comment by samwang1027** [comment]
已发布至 npm 仓库。由于本项目目前是一个完整的 demo，暂不支持 npm install mpvue-zanui 后直接引用。后续会对项目结构做调整的，感谢建议~
